export const ADD = 'ADD';
export const SUB = 'SUB';

export const HEALTH = 'HEALTH';
export const HEALTH_STATUS = 'HEALTH_STATUS';

export const SYSTEM_ERROR = 'SYSTEM_ERROR';

// for MetaMask
export const METAMASK_ACCOUNT = 'METAMASK_ACCOUNT';
export const METAMASK_NETWORK = 'METAMASK_NETWORK';

// for SimpleToken contract
export const SIMPLE_TOKEN_NAME = 'SIMPLE_TOKEN_NAME';
export const SIMPLE_TOKEN_NAME_SUCCESS = 'SIMPLE_TOKEN_NAME_SUCCESS';
export const SIMPLE_TOKEN_SYMBOL = 'SIMPLE_TOKEN_SYMBOL';
export const SIMPLE_TOKEN_SYMBOL_SUCCESS = 'SIMPLE_TOKEN_SYMBOL_SUCCESS';
export const SIMPLE_TOKEN_DECIMALS = 'SIMPLE_TOKEN_DECIMALS';
export const SIMPLE_TOKEN_DECIMALS_SUCCESS = 'SIMPLE_TOKEN_DECIMALS_SUCCESS';

// for showing progress/onloading
export const FETCHING = 'FETCHING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';

// for showing warning message
export const WARNING_OPEN = 'WARNING_OPEN';
export const WARNING_CLOSE = 'WARNING_CLOSE';

// for CryptoHerosToken contract
export const CRYPTOHEROS_TOKEN_NAME = 'CRYPTOHEROS_TOKEN_NAME';
export const CRYPTOHEROS_TOKEN_NAME_SUCCESS = 'CRYPTOHEROS_TOKEN_NAME_SUCCESS';
export const CRYPTOHEROS_TOKEN_SYMBOL = 'CRYPTOHEROS_TOKEN_SYMBOL';
export const CRYPTOHEROS_TOKEN_SYMBOL_SUCCESS = 'CRYPTOHEROS_TOKEN_SYMBOL_SUCCESS';
export const CRYPTOHEROS_TOKEN_TOKEN_URI = 'CRYPTOHEROS_TOKEN_TOKEN_URI';
export const CRYPTOHEROS_TOKEN_TOKEN_URI_SUCCESS = 'CRYPTOHEROS_TOKEN_TOKEN_URI_SUCCESS';
export const CRYPTOHEROS_TOKEN_OWNER_OF = 'CRYPTOHEROS_TOKEN_OWNER_OF';
export const CRYPTOHEROS_TOKEN_OWNER_OF_SUCCESS = 'CRYPTOHEROS_TOKEN_OWNER_OF_SUCCESS';
export const CRYPTOHEROS_TOKEN_TRANSFER_OWNERSHIP = 'CRYPTOHEROS_TOKEN_TRANSFER_OWNERSHIP';
export const CRYPTOHEROS_TOKEN_TRANSFER_OWNERSHIP_SUCCESS = 'CRYPTOHEROS_TOKEN_TRANSFER_OWNERSHIP_SUCCESS';
export const CRYPTOHEROS_TOKEN_GET_OWNED_TOKENS = 'CRYPTOHEROS_TOKEN_GET_OWNED_TOKENS';
export const CRYPTOHEROS_TOKEN_GET_OWNED_TOKENS_SUCCESS = 'CRYPTOHEROS_TOKEN_GET_OWNED_TOKENS_SUCCESS';
